const base='stitch_remix_of_deep_health_ai_mobile_app';
const screens={
  splash:'01._splash_screen',language:'02._language_selection',onboarding1:'onboarding_01_understand_your_wellness',onboarding2:'onboarding_02_scan._understand._track',onboarding3:'onboarding_03_see_your_wellness_journey',signin:'sign_in_deep_health_ai',register:'registration_deep_health_ai',forgot:'forgot_password_deep_health_ai',otp:'otp_verification_deep_health_ai',reset:'reset_password_deep_health_ai',home:'03._home_dashboard_1',plans:'01._plans_subscriptions',purchase:'03._purchase_confirmation',payment:'05._payment_successful',position:'06._face_positioning_hud',scan:'07._live_30_second_scan',processing:'08._scan_processing',success:'09._scan_success',report:'11._wellness_report_summary',breakdown:'ai_wellness_score_breakdown_telemetry',wallet:'09._points_wallet',refer:'11._refer_earn',profile:'16._profile_overview',notifications:'17._notifications_center',settings:'18._settings_privacy',support:'20._help_support_desk'
};
const rules={
 language:[['Continue','onboarding1']],onboarding1:[['Continue','onboarding2'],['Skip','signin']],onboarding2:[['Continue','onboarding3'],['arrow_back','onboarding1']],onboarding3:[['Get Started','signin']],
 signin:[['Sign In','home'],['Create Account','register'],['Forgot Password','forgot']],register:[['Create Account','otp'],['Sign In','signin']],forgot:[['Send Verification','otp']],otp:[['Verify','home'],['Continue','home']],reset:[['Reset','signin']],
 home:[['Start New Scan','position'],['View Full Report','report'],['Reports','report'],['Referrals','refer'],['notifications','notifications'],['person','profile'],['Home','home'],['Reports','report'],['Scan','position'],['Profile','profile']],
 position:[['Begin Scan','scan'],['arrow_back','home']],success:[['View Report','report'],['Back to Dashboard','home']],report:[['Score Breakdown','breakdown'],['arrow_back','home'],['Home','home'],['Reports','report'],['Scan','position'],['Profile','profile']],breakdown:[['arrow_back','report'],['Export','sheet:export']],
 plans:[['Choose Pro','purchase'],['arrow_back','home']],purchase:[['Proceed','payment'],['Cancel','plans'],['arrow_back','plans']],payment:[['Start Wellness Scan','position'],['Go to Dashboard','home']],
 wallet:[['Refer','refer'],['Redeem','plans'],['arrow_back','profile']],refer:[['Copy','toast:Referral code copied'],['arrow_back','wallet']],
 profile:[['Manage Plan','plans'],['Wellness Reports','report'],['Points Wallet','wallet'],['Referrals','refer'],['Notifications','notifications'],['Settings','settings'],['Help','support'],['Log Out','sheet:logout'],['Home','home'],['Reports','report'],['Scan','position'],['Profile','profile']],
 notifications:[['wellness report','report'],['points wallet','wallet'],['arrow_back','profile']],settings:[['Log Out','signin'],['arrow_back','profile']],support:[['Submit','sheet:ticket'],['arrow_back','profile']]
};
const frame=document.querySelector('#screen'),loader=document.querySelector('#loading'),sheet=document.querySelector('#sheet'),scrim=document.querySelector('#scrim'),toast=document.querySelector('#toast'),appNav=document.querySelector('#app-nav');
const navScreens=['home','report','breakdown','plans','profile'];
let current='',timer;
function route(name,replace=false){if(!screens[name])name='splash';current=name;appNav.hidden=!navScreens.includes(name);loader.classList.remove('done');const hash='#/'+name;if(location.hash!==hash){history[replace?'replaceState':'pushState']({screen:name},'',hash)}frame.src=`${base}/${screens[name]}/code.html`;clearTimeout(timer)}
function textOf(el){return `${el.innerText||''} ${el.getAttribute?.('aria-label')||''} ${el.querySelector?.('.material-symbols-outlined')?.textContent||''}`.trim().toLowerCase()}
function wire(){const doc=frame.contentDocument;if(!doc)return;doc.documentElement.style.webkitTapHighlightColor='transparent';const showNav=navScreens.includes(current);appNav.hidden=!showNav;if(showNav){doc.querySelectorAll('nav').forEach(nav=>{if(getComputedStyle(nav).position==='fixed'&&parseFloat(getComputedStyle(nav).bottom)===0)nav.style.display='none'});doc.body.style.paddingBottom='96px'}appNav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.route===(current==='breakdown'?'report':current)));doc.querySelectorAll('button,a,[role=button],.cursor-pointer').forEach(el=>{el.style.cursor='pointer';el.addEventListener('click',e=>{const text=textOf(el);const match=(rules[current]||[]).find(([needle])=>text.includes(needle.toLowerCase()));if(match){e.preventDefault();e.stopPropagation();act(match[1])}})}); if(current==='splash')timer=setTimeout(()=>route('language'),1800);if(current==='scan')timer=setTimeout(()=>route('processing'),4200);if(current==='processing')timer=setTimeout(()=>route('success'),3500)}
function act(action){if(action.startsWith('toast:'))showToast(action.slice(6));else if(action.startsWith('sheet:'))showSheet(action.slice(6));else route(action)}
function showToast(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>toast.hidden=true,2200)}
function showSheet(kind){const content={logout:['Log out of Deep Health AI?','You can sign back in at any time.','Log Out'],export:['Export health record','Your FHIR-compatible wellness report is ready for this prototype demo.','Download Report'],ticket:['Support request submitted','Your demo ticket DH-2048 has been created. We will respond within 24 hours.','Done']}[kind];sheet.innerHTML=`<h2>${content[0]}</h2><p>${content[1]}</p><button>${content[2]}</button><button class="secondary">Cancel</button>`;sheet.hidden=scrim.hidden=false;sheet.querySelector('button').onclick=()=>{closeSheet();if(kind==='logout')route('signin');else showToast(kind==='export'?'FHIR report exported':'Ticket submitted successfully')};sheet.querySelector('.secondary').onclick=closeSheet;scrim.onclick=closeSheet}
function closeSheet(){sheet.hidden=scrim.hidden=true}
frame.addEventListener('load',()=>{loader.classList.add('done');wire()});addEventListener('hashchange',()=>{const name=location.hash.slice(2);if(name!==current)route(name,true)});addEventListener('popstate',()=>{const name=location.hash.slice(2);if(name&&name!==current)route(name,true)});appNav.addEventListener('click',event=>{const button=event.target.closest('button[data-route]');if(button)route(button.dataset.route)});
route(location.hash.slice(2)||'splash',true);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
